version: "3"

services:
  frontend:
    build: ./
    ports:
      - 4200:4200

#  keycloak:
#    image: jboss/keycloak:12.0.4
#    environment:
#      KEYCLOAK_USER: admin
#      KEYCLOAK_PASSWORD: admin
#    volumes:
#      - keycloak_data:/opt/jboss/keycloak/standalone/configuration
#    ports:
#      - 8080:8080

volumes:
  keycloak_data:
